//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PKDSS.CoreLibrary.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PKDSS.CoreLibrary.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;No&quot;: 1,
        ///    &quot;Tanaman&quot;: &quot;Padi&quot;,
        ///    &quot;C1&quot;: 3.5477,
        ///    &quot;C2&quot;: 0.004433,
        ///    &quot;Pupuk&quot;: &quot;Urea&quot;
        ///  },
        ///  {
        ///    &quot;No&quot;: 2,
        ///    &quot;Tanaman&quot;: &quot;Padi&quot;,
        ///    &quot;C1&quot;: 0.024152,
        ///    &quot;C2&quot;: 0.00667,
        ///    &quot;Pupuk&quot;: &quot;SP36&quot;
        ///  },
        ///  {
        ///    &quot;No&quot;: 3,
        ///    &quot;Tanaman&quot;: &quot;Padi&quot;,
        ///    &quot;C1&quot;: 0.059912,
        ///    &quot;C2&quot;: 0.004799,
        ///    &quot;Pupuk&quot;: &quot;KCL&quot;
        ///  },
        ///  {
        ///    &quot;No&quot;: 4,
        ///    &quot;Tanaman&quot;: &quot;Jagung&quot;,
        ///    &quot;C1&quot;: 22.002,
        ///    &quot;C2&quot;: 0.00351,
        ///    &quot;Pupuk&quot;: &quot;Urea&quot;
        ///  },
        ///  {
        ///    &quot;No&quot;: 5,
        ///    &quot;Tanaman&quot;: &quot;Jagung&quot;,
        ///    &quot;C1&quot;: 0.01334,
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;Kabupaten&quot;: &quot;Kabupaten Aceh Barat Daya&quot;,
        ///    &quot;Propinsi&quot;: &quot;Aceh&quot;,
        ///    &quot;Pulau&quot;: &quot;Sumatera&quot;,
        ///    &quot;Pemerintahan&quot;: &quot;Blangpidie&quot;
        ///  },
        ///  {
        ///    &quot;Kabupaten&quot;: &quot;Kabupaten Aceh Barat&quot;,
        ///    &quot;Propinsi&quot;: &quot;Aceh&quot;,
        ///    &quot;Pulau&quot;: &quot;Sumatera&quot;,
        ///    &quot;Pemerintahan&quot;: &quot;Meulaboh&quot;
        ///  },
        ///  {
        ///    &quot;Kabupaten&quot;: &quot;Kabupaten Aceh Besar&quot;,
        ///    &quot;Propinsi&quot;: &quot;Aceh&quot;,
        ///    &quot;Pulau&quot;: &quot;Sumatera&quot;,
        ///    &quot;Pemerintahan&quot;: &quot;Kota Jantho&quot;
        ///  },
        ///  {
        ///    &quot;Kabupaten&quot;: &quot;Kabupaten Aceh Jaya&quot;,
        ///    &quot;Propinsi&quot;: &quot;Aceh&quot;,
        ///    &quot;Pulau&quot;: &quot;Sumate [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Lokasi {
            get {
                return ResourceManager.GetString("Lokasi", resourceCulture);
            }
        }
    }
}
